{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-web/0.2.71/lunula-web-0.2.71.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-web",
    "version": "0.2.71",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.lunula",
          "module": "lunula-core",
          "version": {
            "requires": "0.2.71"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-web-js-0.2.71.klib",
          "url": "lunula-web-js-0.2.71.klib",
          "size": 918695,
          "sha512": "5fd1a1a54f0046d2d40feab63b08d367d171895ff76ec2d26ef7f5ea04bb8accfcb26a88f178602928b0df5ad6861cd99f48e3a553f339bf14e7b5e1ddf3939d",
          "sha256": "439e87169ae86748c11cf28f0986ea681b6ce04b388890c3fe07a93bf5d57cd7",
          "sha1": "23d7c62aeacc88ae126b75140cf33aab06ae2fee",
          "md5": "142310e00f8d63e84ad3ed26dc642ffe"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.lunula",
          "module": "lunula-core",
          "version": {
            "requires": "0.2.71"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-web-js-0.2.71.klib",
          "url": "lunula-web-js-0.2.71.klib",
          "size": 918695,
          "sha512": "5fd1a1a54f0046d2d40feab63b08d367d171895ff76ec2d26ef7f5ea04bb8accfcb26a88f178602928b0df5ad6861cd99f48e3a553f339bf14e7b5e1ddf3939d",
          "sha256": "439e87169ae86748c11cf28f0986ea681b6ce04b388890c3fe07a93bf5d57cd7",
          "sha1": "23d7c62aeacc88ae126b75140cf33aab06ae2fee",
          "md5": "142310e00f8d63e84ad3ed26dc642ffe"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "lunula-web-js-0.2.71-sources.jar",
          "url": "lunula-web-js-0.2.71-sources.jar",
          "size": 421697,
          "sha512": "259db6b88d4dcd5f68750111da89f21b2a25c4ead32e0bf34ce461d1a232b0a324a725b2a03c43a21d1819045b26040971ef3385a11072603b057d2d3b6b34c3",
          "sha256": "09ad77258ffb3eda7cb692ec2fccaed2962abfdefd8e6bf2566fe0a0c586c440",
          "sha1": "483f4777d22e5e105051249793ed68f9f590cd13",
          "md5": "2c9cdc26a01eeefc8a944f5b86d5def3"
        }
      ]
    }
  ]
}
