{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-core/0.2.54/lunula-core-0.2.54.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-core",
    "version": "0.2.54",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-iosSimulatorArm64Main-0.2.54.klib",
          "url": "lunula-core-iossimulatorarm64-0.2.54.klib",
          "size": 165864,
          "sha512": "d305ecbc968b98975219e95740aec5297c08574963a124d12650c026b541888593a7392c7cf93a845c109113a43a88d9da77a499f4c75a225f46dbb2cbc2f2a9",
          "sha256": "904d8876cdfa45d29044dbb885080e4cf297bf2b64c78f5939f75a7030742bf9",
          "sha1": "a17edf3861e5c1ed5d800e9855cde62e377998ae",
          "md5": "cd4417aa77d9aad4a69e006f185dc30a"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "lunula-core-iossimulatorarm64-0.2.54-sources.jar",
          "url": "lunula-core-iossimulatorarm64-0.2.54-sources.jar",
          "size": 51667,
          "sha512": "7f63648ddc49f040f2b43f9cc2e18d4fba9fe7dec4c32ec412c50ce2a08cc39647342c32de0c9771ae9516b15d821e8a46f24543f3c2eb3c979bc85247cb64a4",
          "sha256": "b1d0c2535775be4a0acb9cfc4c839db7879edb7431658e9378359e1cb222a0ff",
          "sha1": "3c5712af96dbdda596f1715fb5ff7f47997b3d44",
          "md5": "cc14ab753f59755b35a65f9ea5d75001"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-iossimulatorarm64-0.2.54-metadata.jar",
          "url": "lunula-core-iossimulatorarm64-0.2.54-metadata.jar",
          "size": 261,
          "sha512": "cf17604f02af71781bb2d914a882a2d439b714bb8fef8fdb75039578bd48ccc4af358175d7af27b3f888167919a649e1963961b65777def718e446d42d324474",
          "sha256": "c1bae6e469274358273cd52a27c6819d580fdf9912197ed61c9694bd2ddaf43b",
          "sha1": "b5583e483a66651f9c62a744de95053b98faa7c2",
          "md5": "711c93a63d0f7d6270235fab27d495db"
        }
      ]
    }
  ]
}
