{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-store/0.2.34/toolkit-store-0.2.34.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-store",
    "version": "0.2.34",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.34"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-iosSimulatorArm64Main-0.2.34.klib",
          "url": "toolkit-store-iossimulatorarm64-0.2.34.klib",
          "size": 61155,
          "sha512": "1556c72bcb6f4583119a9d1296792655fc1e05547506634a1d17108b6241c9c104366364e4a356f9ffe7f1ead550592f78884b87d909ffd46930242ebb3d769a",
          "sha256": "50b577af51b5a8d8f0d087c34aa0596a2462aa9ee97b8bf82d73a2980199a570",
          "sha1": "fd5548ae0b4e5524d7762de6b73b3a728083c146",
          "md5": "b6a9c8ee0cdc5fad0aecc0478a7fab2a"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "toolkit-store-iossimulatorarm64-0.2.34-sources.jar",
          "url": "toolkit-store-iossimulatorarm64-0.2.34-sources.jar",
          "size": 17779,
          "sha512": "e2f6d3ef4c2984fb2d537b8c3c1102a3044da7ff7ba2f2ed72193ca56671133374fb8b803c4e2a83d696a6c5c52ceafcc36c183203070399d132388e790c6645",
          "sha256": "b4dab38a27904aa897f56c2f8b2ccc7c2513fd6508b7101fa8f42b8689234256",
          "sha1": "dd2a80c36e2049e1d96ef2483d5131de4285c613",
          "md5": "3064e8bf869402ff092488e955d7d0c8"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.34"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-iossimulatorarm64-0.2.34-metadata.jar",
          "url": "toolkit-store-iossimulatorarm64-0.2.34-metadata.jar",
          "size": 3865,
          "sha512": "2615264dc99a394370d64500996ac907c5f556586a936413e1496ca3ace0f101f42590f906f48162e647cfaef2e25fd8d414a387f300e2269bccc20c495607b0",
          "sha256": "eac3feaebe015daa59f22efb45ece2c9d1192f135182849f4fc383dbf8e5a3ed",
          "sha1": "63b2c08962a8c413a8d46b3f2ff822e072e29684",
          "md5": "bdc5c1207ccc45cc19916de18606b6b0"
        }
      ]
    }
  ]
}
