{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-store/0.2.36/toolkit-store-0.2.36.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-store",
    "version": "0.2.36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.36"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-iosArm64Main-0.2.36.klib",
          "url": "toolkit-store-iosarm64-0.2.36.klib",
          "size": 61089,
          "sha512": "adab3865a2ad98e150db262c1200155c5d986c488dfd918140afbadd2edd759390eb5874effb8e93752703cf2fda3c9da806fa0c04f511b30720b26f62962312",
          "sha256": "af0a7312f23e6d23abef2f5cae9630f9c7558557f7d3dc6739b839113e53cd6f",
          "sha1": "d17c662a3fd6ba318bc7f4a0844b7d4a1424c671",
          "md5": "4de37e2d92f6048b1166efc6a128efec"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "toolkit-store-iosarm64-0.2.36-sources.jar",
          "url": "toolkit-store-iosarm64-0.2.36-sources.jar",
          "size": 17779,
          "sha512": "e2f6d3ef4c2984fb2d537b8c3c1102a3044da7ff7ba2f2ed72193ca56671133374fb8b803c4e2a83d696a6c5c52ceafcc36c183203070399d132388e790c6645",
          "sha256": "b4dab38a27904aa897f56c2f8b2ccc7c2513fd6508b7101fa8f42b8689234256",
          "sha1": "dd2a80c36e2049e1d96ef2483d5131de4285c613",
          "md5": "3064e8bf869402ff092488e955d7d0c8"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.36"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-iosarm64-0.2.36-metadata.jar",
          "url": "toolkit-store-iosarm64-0.2.36-metadata.jar",
          "size": 3865,
          "sha512": "3d415c6fe61d7950f42fd72ab4ef54e4943ba2566352202612289eb060065e8489ffecb81e68f2940aff07e5c76685f3dba15efd25e48bb57d944b2d42934bfe",
          "sha256": "0a2e4491ae198c8058837762b9be4f62bacb3a9f291a2f75d07429d6fde42612",
          "sha1": "e3f0c2c9056e92b3fff0225dd8fb5c37b066f573",
          "md5": "05bcdb0e95739f6c729b8cea0f471b30"
        }
      ]
    }
  ]
}
