{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-core/0.2.71/lunula-core-0.2.71.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-core",
    "version": "0.2.71",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-iosArm64Main-0.2.71.klib",
          "url": "lunula-core-iosarm64-0.2.71.klib",
          "size": 180698,
          "sha512": "12867ad3dd3b26f55fdf9556c9fbb984fbe5216fa7136f18fe82162d7d3d192cd4a388ac9848021203f264c534bcb4deb405ae6f1719ed112dcd9ef55f83ea70",
          "sha256": "6c831f30c0602d3acaadf72b4b978db3b884671d4ff580f403d3713a2e95932a",
          "sha1": "9b31eb68919a1c0add48f5607f2d92b5083913a6",
          "md5": "59f7de3871f3404630d67c264cce7aba"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "lunula-core-iosarm64-0.2.71-sources.jar",
          "url": "lunula-core-iosarm64-0.2.71-sources.jar",
          "size": 62398,
          "sha512": "43b873bd9d3a1764748e86de102b9a89b1edf1f2d221dda7abb29214722efbd13e47091bbf6e563d20af7a241045ce8bc3dd96edcb98fe365fc2b4d01cda9013",
          "sha256": "43281ae31e0b5eed62718c5e00ed29c84e173f896758ca7057d7ef8d69a53309",
          "sha1": "36743746e8e894067c267c7e5bf6a6ddd8521124",
          "md5": "0109a4ddf9a308488284e0a4443bfaca"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-iosarm64-0.2.71-metadata.jar",
          "url": "lunula-core-iosarm64-0.2.71-metadata.jar",
          "size": 261,
          "sha512": "237710b1cada563307769f179b5f2e87a3b715be3b5a38cc3e8f98a3ef1dabda3057fb195a749c2e791df9960de3db73010430f257130b79ceefd5a3590ed5ab",
          "sha256": "dcce9619474c58330e9738797934a0d5a2bd2c8eec0ad0eb2ad5bb266a41290b",
          "sha1": "963f2c978c6075df376fc5e35651908abfad0f9a",
          "md5": "0517b682a93eb5617bcf4eda5c8de51b"
        }
      ]
    }
  ]
}
