{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-core/0.2.54/lunula-core-0.2.54.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-core",
    "version": "0.2.54",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-js-0.2.54.klib",
          "url": "lunula-core-js-0.2.54.klib",
          "size": 142834,
          "sha512": "007d0e09686f45013bb1e5e008e80ae1a63b1403a24a81840281eb4ea160f28dc6a555dada27eed7b3292de648bbac123441625780aa82676ece380d1f1b56fc",
          "sha256": "a63cf9ac3cebe320af4aa5577d945729e277583642adb7c2147369b2a9f9f866",
          "sha1": "63347166d2041a46a96f46e4ae7ade295574403e",
          "md5": "f720c1182655561dd9b64d2e2da71ac5"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-js-0.2.54.klib",
          "url": "lunula-core-js-0.2.54.klib",
          "size": 142834,
          "sha512": "007d0e09686f45013bb1e5e008e80ae1a63b1403a24a81840281eb4ea160f28dc6a555dada27eed7b3292de648bbac123441625780aa82676ece380d1f1b56fc",
          "sha256": "a63cf9ac3cebe320af4aa5577d945729e277583642adb7c2147369b2a9f9f866",
          "sha1": "63347166d2041a46a96f46e4ae7ade295574403e",
          "md5": "f720c1182655561dd9b64d2e2da71ac5"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "lunula-core-js-0.2.54-sources.jar",
          "url": "lunula-core-js-0.2.54-sources.jar",
          "size": 51667,
          "sha512": "7f63648ddc49f040f2b43f9cc2e18d4fba9fe7dec4c32ec412c50ce2a08cc39647342c32de0c9771ae9516b15d821e8a46f24543f3c2eb3c979bc85247cb64a4",
          "sha256": "b1d0c2535775be4a0acb9cfc4c839db7879edb7431658e9378359e1cb222a0ff",
          "sha1": "3c5712af96dbdda596f1715fb5ff7f47997b3d44",
          "md5": "cc14ab753f59755b35a65f9ea5d75001"
        }
      ]
    }
  ]
}
