{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-web/0.2.55/lunula-web-0.2.55.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-web",
    "version": "0.2.55",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.lunula",
          "module": "lunula-core",
          "version": {
            "requires": "0.2.55"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-web-js-0.2.55.klib",
          "url": "lunula-web-js-0.2.55.klib",
          "size": 850796,
          "sha512": "230391358e379eeee03be61384f5c093d1bd9560c594dcc42b006d460d4ab53f2618b73da2a00eb81738d7c5b44325da0e80e539ca0d8423859b7b9ca3d31819",
          "sha256": "2a131b7cb2458a1c88a02018d7fd592641600740514a1320595b538c699823dd",
          "sha1": "7589c035337ef65473e6516249fc41053ddd581b",
          "md5": "178da4a49d177b05455b988be3bea0e8"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.lunula",
          "module": "lunula-core",
          "version": {
            "requires": "0.2.55"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-web-js-0.2.55.klib",
          "url": "lunula-web-js-0.2.55.klib",
          "size": 850796,
          "sha512": "230391358e379eeee03be61384f5c093d1bd9560c594dcc42b006d460d4ab53f2618b73da2a00eb81738d7c5b44325da0e80e539ca0d8423859b7b9ca3d31819",
          "sha256": "2a131b7cb2458a1c88a02018d7fd592641600740514a1320595b538c699823dd",
          "sha1": "7589c035337ef65473e6516249fc41053ddd581b",
          "md5": "178da4a49d177b05455b988be3bea0e8"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "lunula-web-js-0.2.55-sources.jar",
          "url": "lunula-web-js-0.2.55-sources.jar",
          "size": 374765,
          "sha512": "cd086f3137a416561555aaba9e12c782ff00adfdd08402210d041b5884ba2cb1ba60e2dd9c834b904215fd3a5d478004726225ee06d00357a9fb01f727015c86",
          "sha256": "f8198d68818078cfd7d203d10e4e43b57e44f35d6b32f361b556a82a1727a65b",
          "sha1": "89fc565bb5bb0dc9358bcdb35b6be4a6e9fc846b",
          "md5": "101b8b2cd4c1e1633d6de9ee30b11cbb"
        }
      ]
    }
  ]
}
