{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-compose/0.2.60/lunula-compose-0.2.60.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-compose",
    "version": "0.2.60",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.lunula",
          "module": "lunula-core",
          "version": {
            "requires": "0.2.60"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-compose-release.aar",
          "url": "lunula-compose-android-0.2.60.aar",
          "size": 29872,
          "sha512": "c33e4093062c18e94a461dc8b45d42e51c4fa5a5f2ea13fb85c98a3caa518d96b1c662cb34813a1d033428006312a0af94f4e0c9d4d2376a05e86ebccbb128f7",
          "sha256": "b64765ceb980c53ab567456baeb378e60f58e9104b8e68ab9998b76acd247e4c",
          "sha1": "453fc1daaf1f7c6272815f18c98f0ae5eac527db",
          "md5": "2f424340021e5d4c111d7bfbabc500db"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.lunula",
          "module": "lunula-core",
          "version": {
            "requires": "0.2.60"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "lunula-compose-release.aar",
          "url": "lunula-compose-android-0.2.60.aar",
          "size": 29872,
          "sha512": "c33e4093062c18e94a461dc8b45d42e51c4fa5a5f2ea13fb85c98a3caa518d96b1c662cb34813a1d033428006312a0af94f4e0c9d4d2376a05e86ebccbb128f7",
          "sha256": "b64765ceb980c53ab567456baeb378e60f58e9104b8e68ab9998b76acd247e4c",
          "sha1": "453fc1daaf1f7c6272815f18c98f0ae5eac527db",
          "md5": "2f424340021e5d4c111d7bfbabc500db"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "lunula-compose-android-0.2.60-sources.jar",
          "url": "lunula-compose-android-0.2.60-sources.jar",
          "size": 5640,
          "sha512": "c8a81e5c5088c44475d6d69bebaf21aaedeb9cec73a717ceff9e2d30d102b9ee15fb04ef8b10e7e6586a28a394e1d69479b4148a2b50397ee6e35cf522ecb98f",
          "sha256": "2c0e5c4c1f4fe2d1828a0319658284def9e811c3bcab153e8bd3e4c878e84c47",
          "sha1": "866300d7c0979e59b50041ba034a4ebe4fe1b753",
          "md5": "34c8d35d812ec9ee8e8afdf8d5bec62e"
        }
      ]
    }
  ]
}
