{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-web/0.2.61/lunula-web-0.2.61.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-web",
    "version": "0.2.61",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.lunula",
          "module": "lunula-core",
          "version": {
            "requires": "0.2.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-web-js-0.2.61.klib",
          "url": "lunula-web-js-0.2.61.klib",
          "size": 853390,
          "sha512": "556ddbb6224ab6f1c80882074955573d9f9e1a45789d3653abcc22a97bf208cf8459e77e4c5ce9e067b9ec50e3a7453cb1a016776ab129c015e7c99eb28ca0a9",
          "sha256": "e009d41206da3a7c6a4267379f9f376b0c8fb06074d0619e481851cdb44472b8",
          "sha1": "507455afb19812ed69b3a1740798807d19d43b68",
          "md5": "b30480dfab123c31492853c8c0ecf515"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.lunula",
          "module": "lunula-core",
          "version": {
            "requires": "0.2.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-web-js-0.2.61.klib",
          "url": "lunula-web-js-0.2.61.klib",
          "size": 853390,
          "sha512": "556ddbb6224ab6f1c80882074955573d9f9e1a45789d3653abcc22a97bf208cf8459e77e4c5ce9e067b9ec50e3a7453cb1a016776ab129c015e7c99eb28ca0a9",
          "sha256": "e009d41206da3a7c6a4267379f9f376b0c8fb06074d0619e481851cdb44472b8",
          "sha1": "507455afb19812ed69b3a1740798807d19d43b68",
          "md5": "b30480dfab123c31492853c8c0ecf515"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "lunula-web-js-0.2.61-sources.jar",
          "url": "lunula-web-js-0.2.61-sources.jar",
          "size": 376085,
          "sha512": "0b911c5c43576833676703c2eb66cdfa5534b1f55581720e43f10a1b84843571fa513bf4cdae4982690b9fa294598a766e4e5e91621bef8030ab5a8a7f604774",
          "sha256": "494b67ca6a2122f08248f94c89ccfc08adeaf059661c21704f8ca36c00d7cb4f",
          "sha1": "974c2bc44617a2cbeb4842b0a90517d397f04310",
          "md5": "6f86ce21274044e764f5d6785ec50880"
        }
      ]
    }
  ]
}
