{
  "formatVersion": "1.1",
  "component": {
    "group": "se.soderbjorn.lunula",
    "module": "lunula-core",
    "version": "0.2.71",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-metadata-0.2.71.jar",
          "url": "lunula-core-0.2.71.jar",
          "size": 15600,
          "sha512": "b98f03f4f6c762c4f40fc6e87f6bc83801d72f28131a91f1cca9a5be284dd8ec110e3b39c84df96433d717d97091622886a5e8d777d6966bca0a9bc9cc594e3a",
          "sha256": "7f6988d74448ae8b85736237da62c7664ca4b2a462279ffebb9b36f2264e9dd0",
          "sha1": "d82e1efe9d04b35746bae0c14306bcff8af202b5",
          "md5": "13f78bcb5b67c5c6a6abd769e6718067"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "lunula-core-kotlin-0.2.71-sources.jar",
          "url": "lunula-core-0.2.71-sources.jar",
          "size": 62398,
          "sha512": "43b873bd9d3a1764748e86de102b9a89b1edf1f2d221dda7abb29214722efbd13e47091bbf6e563d20af7a241045ce8bc3dd96edcb98fe365fc2b4d01cda9013",
          "sha256": "43281ae31e0b5eed62718c5e00ed29c84e173f896758ca7057d7ef8d69a53309",
          "sha1": "36743746e8e894067c267c7e5bf6a6ddd8521124",
          "md5": "0109a4ddf9a308488284e0a4443bfaca"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../lunula-core-android/0.2.71/lunula-core-android-0.2.71.module",
        "group": "se.soderbjorn.lunula",
        "module": "lunula-core-android",
        "version": "0.2.71"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../lunula-core-android/0.2.71/lunula-core-android-0.2.71.module",
        "group": "se.soderbjorn.lunula",
        "module": "lunula-core-android",
        "version": "0.2.71"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../lunula-core-android/0.2.71/lunula-core-android-0.2.71.module",
        "group": "se.soderbjorn.lunula",
        "module": "lunula-core-android",
        "version": "0.2.71"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lunula-core-iosarm64/0.2.71/lunula-core-iosarm64-0.2.71.module",
        "group": "se.soderbjorn.lunula",
        "module": "lunula-core-iosarm64",
        "version": "0.2.71"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lunula-core-iosarm64/0.2.71/lunula-core-iosarm64-0.2.71.module",
        "group": "se.soderbjorn.lunula",
        "module": "lunula-core-iosarm64",
        "version": "0.2.71"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lunula-core-iosarm64/0.2.71/lunula-core-iosarm64-0.2.71.module",
        "group": "se.soderbjorn.lunula",
        "module": "lunula-core-iosarm64",
        "version": "0.2.71"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lunula-core-iossimulatorarm64/0.2.71/lunula-core-iossimulatorarm64-0.2.71.module",
        "group": "se.soderbjorn.lunula",
        "module": "lunula-core-iossimulatorarm64",
        "version": "0.2.71"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lunula-core-iossimulatorarm64/0.2.71/lunula-core-iossimulatorarm64-0.2.71.module",
        "group": "se.soderbjorn.lunula",
        "module": "lunula-core-iossimulatorarm64",
        "version": "0.2.71"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lunula-core-iossimulatorarm64/0.2.71/lunula-core-iossimulatorarm64-0.2.71.module",
        "group": "se.soderbjorn.lunula",
        "module": "lunula-core-iossimulatorarm64",
        "version": "0.2.71"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../lunula-core-js/0.2.71/lunula-core-js-0.2.71.module",
        "group": "se.soderbjorn.lunula",
        "module": "lunula-core-js",
        "version": "0.2.71"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../lunula-core-js/0.2.71/lunula-core-js-0.2.71.module",
        "group": "se.soderbjorn.lunula",
        "module": "lunula-core-js",
        "version": "0.2.71"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../lunula-core-js/0.2.71/lunula-core-js-0.2.71.module",
        "group": "se.soderbjorn.lunula",
        "module": "lunula-core-js",
        "version": "0.2.71"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lunula-core-jvm/0.2.71/lunula-core-jvm-0.2.71.module",
        "group": "se.soderbjorn.lunula",
        "module": "lunula-core-jvm",
        "version": "0.2.71"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lunula-core-jvm/0.2.71/lunula-core-jvm-0.2.71.module",
        "group": "se.soderbjorn.lunula",
        "module": "lunula-core-jvm",
        "version": "0.2.71"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lunula-core-jvm/0.2.71/lunula-core-jvm-0.2.71.module",
        "group": "se.soderbjorn.lunula",
        "module": "lunula-core-jvm",
        "version": "0.2.71"
      }
    }
  ]
}
