{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-web/0.2.62/lunula-web-0.2.62.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-web",
    "version": "0.2.62",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.lunula",
          "module": "lunula-core",
          "version": {
            "requires": "0.2.62"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-web-js-0.2.62.klib",
          "url": "lunula-web-js-0.2.62.klib",
          "size": 865262,
          "sha512": "1dca9a17dbad9fe77d99a4f58fd08091d7cec8852b79bafa4477fdfa376ad908883e293d7cb28cd9b6e63387f7511faaa2ddea2aa009df1b754af59621d29aa1",
          "sha256": "f3e0341f0fff420be584067ffbe723381c3dd7408df2c21092d583c844488192",
          "sha1": "b2885c45aed8c75268f4699a5826a0360127802f",
          "md5": "c40aebbffee63faf67d9c31dfb65aff6"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.lunula",
          "module": "lunula-core",
          "version": {
            "requires": "0.2.62"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-web-js-0.2.62.klib",
          "url": "lunula-web-js-0.2.62.klib",
          "size": 865262,
          "sha512": "1dca9a17dbad9fe77d99a4f58fd08091d7cec8852b79bafa4477fdfa376ad908883e293d7cb28cd9b6e63387f7511faaa2ddea2aa009df1b754af59621d29aa1",
          "sha256": "f3e0341f0fff420be584067ffbe723381c3dd7408df2c21092d583c844488192",
          "sha1": "b2885c45aed8c75268f4699a5826a0360127802f",
          "md5": "c40aebbffee63faf67d9c31dfb65aff6"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "lunula-web-js-0.2.62-sources.jar",
          "url": "lunula-web-js-0.2.62-sources.jar",
          "size": 382389,
          "sha512": "fd686ede17368f8f133e061e92361cce929d169a90adf2dfb4bb75a3ea6ded71faff47c53d2c4424da3bae6cf273ef9cb1dad4514311e812dd0311939cbecd1c",
          "sha256": "41bb36f74548a89ee1624f2ba02de8780ac3fd69daa553b00a10d7ee77b941d6",
          "sha1": "8d681c34e8684656b594a8d8f0700a0402a9413a",
          "md5": "3b0bd1c62d9e8cffd589d53d7ea7a9fa"
        }
      ]
    }
  ]
}
