{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-core/0.2.64/lunula-core-0.2.64.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-core",
    "version": "0.2.64",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-iosSimulatorArm64Main-0.2.64.klib",
          "url": "lunula-core-iossimulatorarm64-0.2.64.klib",
          "size": 177800,
          "sha512": "e7acf11e7fcb53bdb1012d07bc247c73b6f94913543175d734c0c7f72f3db64d2058cf1fb3954afbce3da2bed930fd96d59b81cf27255450d8706f0bbf96ef8a",
          "sha256": "b0ca34ffe44d2e7aa45555f1d9ef9c12f7c7456f63e0c6e27550a825feb2c7f0",
          "sha1": "0d3d8e7d0bfe182493601a1623500029ebd3eb69",
          "md5": "937ea302e712d44f5ed366d324c30506"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "lunula-core-iossimulatorarm64-0.2.64-sources.jar",
          "url": "lunula-core-iossimulatorarm64-0.2.64-sources.jar",
          "size": 60183,
          "sha512": "5863c1ed2855f567a5bf249f66b3ec444e2ef8ed50ad90c818bcbdae15f5e9cb03fbd6eab8dde23a3c4f671da6cd1261fa2a44f612230eabfad6dce2b2ebe775",
          "sha256": "a8467f5f7638e6cc2e9c3c700bd397a5ad8d4b792a80bf83a8aad249a960f81c",
          "sha1": "02e1b688c16da8d448e605ff82ff763a9c055e90",
          "md5": "a550be4c6ad0392b7b303e0b0e9b5db1"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-iossimulatorarm64-0.2.64-metadata.jar",
          "url": "lunula-core-iossimulatorarm64-0.2.64-metadata.jar",
          "size": 261,
          "sha512": "6b3361add9c9ac030bb30c01dc28452c8fa2c21341aae6bb2078491f42875615386c0ceb7baa220df6c3916734b742f8138ff5bedc8c1571bbd492b36bdb83d6",
          "sha256": "132ec571f0c581bef489063c70f85fe64362265294d4b4705878c10a5e9ac11b",
          "sha1": "887e092fa792a0b48fccaac6b4293bdd70506f1f",
          "md5": "0bcddca0b64f341344fbd5778eb13d14"
        }
      ]
    }
  ]
}
