{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-core/0.2.64/lunula-core-0.2.64.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-core",
    "version": "0.2.64",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-jvm-0.2.64.jar",
          "url": "lunula-core-jvm-0.2.64.jar",
          "size": 126505,
          "sha512": "14ca4fdf5a801014c3da0ec1fa96bc4ffd19071e6114c50c702538112fd849ceb3deb08de00ffa497aa35f48c4317a5dca4442a5ac1269d3f78c04702c93423b",
          "sha256": "ab8e013d0be27bfb0349501aac8787fff2870fef48d08c7e107fdc7e7976cfc0",
          "sha1": "f5460f356c66978a529f295d50399c6834bfc64d",
          "md5": "6c9fa23e66ad59cb4a8c00e65b61c337"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-jvm-0.2.64.jar",
          "url": "lunula-core-jvm-0.2.64.jar",
          "size": 126505,
          "sha512": "14ca4fdf5a801014c3da0ec1fa96bc4ffd19071e6114c50c702538112fd849ceb3deb08de00ffa497aa35f48c4317a5dca4442a5ac1269d3f78c04702c93423b",
          "sha256": "ab8e013d0be27bfb0349501aac8787fff2870fef48d08c7e107fdc7e7976cfc0",
          "sha1": "f5460f356c66978a529f295d50399c6834bfc64d",
          "md5": "6c9fa23e66ad59cb4a8c00e65b61c337"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lunula-core-jvm-0.2.64-sources.jar",
          "url": "lunula-core-jvm-0.2.64-sources.jar",
          "size": 60183,
          "sha512": "5863c1ed2855f567a5bf249f66b3ec444e2ef8ed50ad90c818bcbdae15f5e9cb03fbd6eab8dde23a3c4f671da6cd1261fa2a44f612230eabfad6dce2b2ebe775",
          "sha256": "a8467f5f7638e6cc2e9c3c700bd397a5ad8d4b792a80bf83a8aad249a960f81c",
          "sha1": "02e1b688c16da8d448e605ff82ff763a9c055e90",
          "md5": "a550be4c6ad0392b7b303e0b0e9b5db1"
        }
      ]
    }
  ]
}
