{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-core/0.2.67/lunula-core-0.2.67.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-core",
    "version": "0.2.67",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-iosArm64Main-0.2.67.klib",
          "url": "lunula-core-iosarm64-0.2.67.klib",
          "size": 179087,
          "sha512": "2b174791574db22f130c4895d416099c4399a303780c46a705333adb3bb8581f72258ed63f1eb0e3e09da98d620ebb5f7d335ca7698f324e6e2d9523df6ed176",
          "sha256": "cecc1d55d07e4c0f36b26276aef783ad82c317c078a07cee78fb750aafe428f5",
          "sha1": "73c4885f7d99edf889fed45701ada5d944eda631",
          "md5": "148892df589d7f91b9d7858c2123fa20"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "lunula-core-iosarm64-0.2.67-sources.jar",
          "url": "lunula-core-iosarm64-0.2.67-sources.jar",
          "size": 61079,
          "sha512": "102db2b97a48b465efdf5975959bd14849ef65b8283c5a2f6e4f143b17e944d82f1c174e04a3cf52483f7313a230a6cba2db52d282a311af5fa497789ad8e353",
          "sha256": "c065e9de8017e55497a301dc068b6304ca49417ce1510e6f77c3445362eb9965",
          "sha1": "799c416f3d21ed5541184d6b11b01d59c182685a",
          "md5": "3e2eb269a859c901ef4513bdcfc5b14c"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-iosarm64-0.2.67-metadata.jar",
          "url": "lunula-core-iosarm64-0.2.67-metadata.jar",
          "size": 261,
          "sha512": "bf22c6014fa863eb05938da077d799e649bec2ac93d4eb9f07bc11e3c0fc2b43ff96ed50fa61102025398d140ab6dc2d5ccc5835e44bc1547067dfda23df9011",
          "sha256": "faf290d9cfbb9e388b413683f0c81883bb4532f4612262b1bb53b238b6741f06",
          "sha1": "44f08f845c69eb3cfd4aec26ae324f2adf00be19",
          "md5": "a03be546209aace2c5731e8c49424c47"
        }
      ]
    }
  ]
}
