{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-core/0.2.61/lunula-core-0.2.61.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-core",
    "version": "0.2.61",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-iosArm64Main-0.2.61.klib",
          "url": "lunula-core-iosarm64-0.2.61.klib",
          "size": 177734,
          "sha512": "3848f3b63943ed621c3578d9a5937a09b7b764d6eb023eb88df666a923b5c451ddd37e97b4945c5c6775030c6208a06b6763cc019f7785610c734b863aab11a1",
          "sha256": "f44d453eba694f43421f06798908d5bf0a38db3e43781a68008aaa7d3d83f490",
          "sha1": "868483452c54ead9065f2eb94603b4b9d63d34fa",
          "md5": "42c40b525f0aa3eda3839241136f8c52"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "lunula-core-iosarm64-0.2.61-sources.jar",
          "url": "lunula-core-iosarm64-0.2.61-sources.jar",
          "size": 60183,
          "sha512": "5863c1ed2855f567a5bf249f66b3ec444e2ef8ed50ad90c818bcbdae15f5e9cb03fbd6eab8dde23a3c4f671da6cd1261fa2a44f612230eabfad6dce2b2ebe775",
          "sha256": "a8467f5f7638e6cc2e9c3c700bd397a5ad8d4b792a80bf83a8aad249a960f81c",
          "sha1": "02e1b688c16da8d448e605ff82ff763a9c055e90",
          "md5": "a550be4c6ad0392b7b303e0b0e9b5db1"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-iosarm64-0.2.61-metadata.jar",
          "url": "lunula-core-iosarm64-0.2.61-metadata.jar",
          "size": 261,
          "sha512": "65a39f98b94d5e85078e89b1677647baa01cb55478525b3dfdce1bfab8770b634bb2c54ccc07735680785f1ed2ffeadc19e8430903209a7cf59db2e181c7616d",
          "sha256": "21132d57ab90b5d1bc9051cab4a55f5c32bc3c710e121ce09f4e8bce98d0371d",
          "sha1": "2748b415130b2d7a136b71d7f27702ad42612430",
          "md5": "5eaf367cd9b325200e55b848cb04d0c2"
        }
      ]
    }
  ]
}
