{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-core/0.2.66/lunula-core-0.2.66.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-core",
    "version": "0.2.66",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-iosSimulatorArm64Main-0.2.66.klib",
          "url": "lunula-core-iossimulatorarm64-0.2.66.klib",
          "size": 179153,
          "sha512": "e75c6ec28ef5fada6a0d43f5932b29364e9a0d8279b2995a569c7ead068b8e2187c82b52b32b4622b95f45aa0a8a52b6b1fe5a2a6d7d59478faf16e2affefab5",
          "sha256": "d3cbd436ee3266221cf8c956dbd0315ca95993c49ea5cb7dda1bb9ea5eaec560",
          "sha1": "6f95d76aaebaf1b4a8db8ecbaf5a7f5afb69e796",
          "md5": "3a3aecbe04ec4461ad5a98f2f20fdece"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "lunula-core-iossimulatorarm64-0.2.66-sources.jar",
          "url": "lunula-core-iossimulatorarm64-0.2.66-sources.jar",
          "size": 61079,
          "sha512": "102db2b97a48b465efdf5975959bd14849ef65b8283c5a2f6e4f143b17e944d82f1c174e04a3cf52483f7313a230a6cba2db52d282a311af5fa497789ad8e353",
          "sha256": "c065e9de8017e55497a301dc068b6304ca49417ce1510e6f77c3445362eb9965",
          "sha1": "799c416f3d21ed5541184d6b11b01d59c182685a",
          "md5": "3e2eb269a859c901ef4513bdcfc5b14c"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-iossimulatorarm64-0.2.66-metadata.jar",
          "url": "lunula-core-iossimulatorarm64-0.2.66-metadata.jar",
          "size": 261,
          "sha512": "88642b356d62846e6cbbeac331ac618aa9084ff4b0f82b920bff527f39a88433c56a97ecd0f10ac4032b7aae3c70e5d3cd684f980b4ecf2fa855c6c18334e69b",
          "sha256": "6e391d8eed262588dc7010c24cd811611a085736b5e84d96e4045ab52149426c",
          "sha1": "e02672245db9972373e2dea8bf4b8a25eb7ae35f",
          "md5": "0e424396af8bf0684f774129a3f6ebf4"
        }
      ]
    }
  ]
}
