{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-core/0.2.71/lunula-core-0.2.71.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-core",
    "version": "0.2.71",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-js-0.2.71.klib",
          "url": "lunula-core-js-0.2.71.klib",
          "size": 151973,
          "sha512": "c1f33a8552db92e6a9b63262a2dca38a77c10f48896091e0a7bcdba19a3a71c76b1d57182f66885440860b9dddb6db4ed1a55fc8b2ebef28b7fd42034cb25e16",
          "sha256": "d1e3c9b26ed1fcb7724fae94a9d5689be3051ae460b46a4c3e70c431f0c8742f",
          "sha1": "c01d2f5bb2696fc1d97e97d0b9ecd014ef2d626d",
          "md5": "c30a790abe8b1777bc39efeb451dc450"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-js-0.2.71.klib",
          "url": "lunula-core-js-0.2.71.klib",
          "size": 151973,
          "sha512": "c1f33a8552db92e6a9b63262a2dca38a77c10f48896091e0a7bcdba19a3a71c76b1d57182f66885440860b9dddb6db4ed1a55fc8b2ebef28b7fd42034cb25e16",
          "sha256": "d1e3c9b26ed1fcb7724fae94a9d5689be3051ae460b46a4c3e70c431f0c8742f",
          "sha1": "c01d2f5bb2696fc1d97e97d0b9ecd014ef2d626d",
          "md5": "c30a790abe8b1777bc39efeb451dc450"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "lunula-core-js-0.2.71-sources.jar",
          "url": "lunula-core-js-0.2.71-sources.jar",
          "size": 62398,
          "sha512": "43b873bd9d3a1764748e86de102b9a89b1edf1f2d221dda7abb29214722efbd13e47091bbf6e563d20af7a241045ce8bc3dd96edcb98fe365fc2b4d01cda9013",
          "sha256": "43281ae31e0b5eed62718c5e00ed29c84e173f896758ca7057d7ef8d69a53309",
          "sha1": "36743746e8e894067c267c7e5bf6a6ddd8521124",
          "md5": "0109a4ddf9a308488284e0a4443bfaca"
        }
      ]
    }
  ]
}
