{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-core/0.2.36/toolkit-core-0.2.36.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-core",
    "version": "0.2.36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-iosSimulatorArm64Main-0.2.36.klib",
          "url": "toolkit-core-iossimulatorarm64-0.2.36.klib",
          "size": 135467,
          "sha512": "c64b00fe9978dbedd94e9fd4e81d5ae313a8be0f68b2bc5e5ea2c8524fea0877f6e5ec0de009a9b619b4199ad19a29910387a051baa6a95f79b404def4ea3430",
          "sha256": "88f0884db3f620c01099a2965c603065db8d25f3539641b150630ff6635be374",
          "sha1": "8fcdb3849a0e9f6d8fe7e01c44392d9000ece5c0",
          "md5": "0a65cb4f12ea9ff2ca67cc1ea66223f8"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "toolkit-core-iossimulatorarm64-0.2.36-sources.jar",
          "url": "toolkit-core-iossimulatorarm64-0.2.36-sources.jar",
          "size": 41199,
          "sha512": "e04e38c67c9d1a19e14bf4f7c02d2e9eb3cad2bd0ff39c56ca41bd60a881bbe352d9a76b95120045eff43582f5e3397e54dd28aeab7bf9c529e09399a80adb97",
          "sha256": "d1d98b6ffa44abf5bf723ce841ae8490b3eee1a7cdd525f1d185d2c79998271b",
          "sha1": "e8cb8f04ed161f0dedd5bf7b71e4867e61572134",
          "md5": "f206c236df63c37a52478b5b1ccec7a6"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-iossimulatorarm64-0.2.36-metadata.jar",
          "url": "toolkit-core-iossimulatorarm64-0.2.36-metadata.jar",
          "size": 261,
          "sha512": "1b820d0616c64fe103f9b3293d443b4d27ae3247cd8b6641cf2bcd209b251d565e0725953e7fb57ce12084050b0707a00899653dc3a2126d08b6f01129b9ea2f",
          "sha256": "68e7874c39d7d13c4ebf0cef6353f044ba9b279d37b530aaada976186b35cafa",
          "sha1": "0cac345492d05f8884512d114c9a16c898d521d7",
          "md5": "79ed10049c15df3a0c2da6257a8a7441"
        }
      ]
    }
  ]
}
