{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-web/0.2.69/lunula-web-0.2.69.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-web",
    "version": "0.2.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.lunula",
          "module": "lunula-core",
          "version": {
            "requires": "0.2.69"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-web-js-0.2.69.klib",
          "url": "lunula-web-js-0.2.69.klib",
          "size": 911117,
          "sha512": "57f7100e8691e96d7899679e4e86e769f9551efd70013e1e0dc6cc0d0e3b35f262a13a64bda4ea777be2fe7a5d93a8a7440f787f081d4975cdca8e851a6f1266",
          "sha256": "e1623f9cd0fc65d00ca07b09c36b86a1b41879247fc15ec256152ba769f483e4",
          "sha1": "84967326dacc6eb9da4452b039cc927eee69a184",
          "md5": "2f731aec23e500408fc506d268b24c3a"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.lunula",
          "module": "lunula-core",
          "version": {
            "requires": "0.2.69"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-web-js-0.2.69.klib",
          "url": "lunula-web-js-0.2.69.klib",
          "size": 911117,
          "sha512": "57f7100e8691e96d7899679e4e86e769f9551efd70013e1e0dc6cc0d0e3b35f262a13a64bda4ea777be2fe7a5d93a8a7440f787f081d4975cdca8e851a6f1266",
          "sha256": "e1623f9cd0fc65d00ca07b09c36b86a1b41879247fc15ec256152ba769f483e4",
          "sha1": "84967326dacc6eb9da4452b039cc927eee69a184",
          "md5": "2f731aec23e500408fc506d268b24c3a"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "lunula-web-js-0.2.69-sources.jar",
          "url": "lunula-web-js-0.2.69-sources.jar",
          "size": 412542,
          "sha512": "aa5e2c95dfc4fbdb1da42d11aaf17a96489df17f566085a1153b6436c6453f27f0f4e0891ce08da76dd0133425e72c1ff4cb734d12358182a1994d7c32f74e9b",
          "sha256": "6c62919ded777c9aa0a1aca4a9b938c3004b54717b22d21fd26b0c629e7648f1",
          "sha1": "f5045bd758d009b32d6daf7b8d8310bccb03ee58",
          "md5": "077fb8ca8d67b34bc68980bf84193d38"
        }
      ]
    }
  ]
}
