{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-web/0.2.54/lunula-web-0.2.54.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-web",
    "version": "0.2.54",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.lunula",
          "module": "lunula-core",
          "version": {
            "requires": "0.2.54"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-web-js-0.2.54.klib",
          "url": "lunula-web-js-0.2.54.klib",
          "size": 840835,
          "sha512": "b259420ba2828b2b6ee04c3aa4a0a452e6e9164d7d69d78260272638a6d085da1c6fd3aed4721103239b954d3ea6980ff707ce473e840f9d67893c1997fbaf5b",
          "sha256": "471d8fccc6234058e7e3574e3517b98de52d29d490363006f3548e832324404f",
          "sha1": "beb70e0d65bd06c31c23af4b25ce9c97ab827488",
          "md5": "1fe1577123e32cbdf48860c3e2ccefec"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.lunula",
          "module": "lunula-core",
          "version": {
            "requires": "0.2.54"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-web-js-0.2.54.klib",
          "url": "lunula-web-js-0.2.54.klib",
          "size": 840835,
          "sha512": "b259420ba2828b2b6ee04c3aa4a0a452e6e9164d7d69d78260272638a6d085da1c6fd3aed4721103239b954d3ea6980ff707ce473e840f9d67893c1997fbaf5b",
          "sha256": "471d8fccc6234058e7e3574e3517b98de52d29d490363006f3548e832324404f",
          "sha1": "beb70e0d65bd06c31c23af4b25ce9c97ab827488",
          "md5": "1fe1577123e32cbdf48860c3e2ccefec"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "lunula-web-js-0.2.54-sources.jar",
          "url": "lunula-web-js-0.2.54-sources.jar",
          "size": 368930,
          "sha512": "031327700aa70125fbbd54314cfb267f3dbe7d89ebc5617cca18ab02278282396a20a95f596a9bde130adcbc5b2704c7b902a6ecfd99209f2e98168da189fb18",
          "sha256": "97780d434eaefd6999b2bb8417d6d844f744e52df7f77d9a32e6a3275c672c23",
          "sha1": "d537f9727012a0c7e15d2028a3e6b2e8a9a32059",
          "md5": "1590fa8607bd3c108b382d74339f5b51"
        }
      ]
    }
  ]
}
