{
  "formatVersion": "1.1",
  "component": {
    "group": "se.soderbjorn.lunula",
    "module": "lunula-compose",
    "version": "0.2.60",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.lunula",
          "module": "lunula-core",
          "version": {
            "requires": "0.2.60"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-compose-metadata-0.2.60.jar",
          "url": "lunula-compose-0.2.60.jar",
          "size": 758,
          "sha512": "fd6b7c202cb74825caa6f98a7e8ad792353947be3d550ce0937483932e9ecb02144ba78b7faba960e8b2ecbe9b43ef27e1cde7b934ea2a9f9ada7df370c9690d",
          "sha256": "7810574d937019395888357b3d38be68dbd5a9657a04eb55f6e5dd560bf258f1",
          "sha1": "f3eb6d49113cead7792ba14515c9838fb17f5055",
          "md5": "afe4e2733eb18555a6bc3da68f6361a0"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "lunula-compose-kotlin-0.2.60-sources.jar",
          "url": "lunula-compose-0.2.60-sources.jar",
          "size": 5640,
          "sha512": "c8a81e5c5088c44475d6d69bebaf21aaedeb9cec73a717ceff9e2d30d102b9ee15fb04ef8b10e7e6586a28a394e1d69479b4148a2b50397ee6e35cf522ecb98f",
          "sha256": "2c0e5c4c1f4fe2d1828a0319658284def9e811c3bcab153e8bd3e4c878e84c47",
          "sha1": "866300d7c0979e59b50041ba034a4ebe4fe1b753",
          "md5": "34c8d35d812ec9ee8e8afdf8d5bec62e"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../lunula-compose-android/0.2.60/lunula-compose-android-0.2.60.module",
        "group": "se.soderbjorn.lunula",
        "module": "lunula-compose-android",
        "version": "0.2.60"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../lunula-compose-android/0.2.60/lunula-compose-android-0.2.60.module",
        "group": "se.soderbjorn.lunula",
        "module": "lunula-compose-android",
        "version": "0.2.60"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../lunula-compose-android/0.2.60/lunula-compose-android-0.2.60.module",
        "group": "se.soderbjorn.lunula",
        "module": "lunula-compose-android",
        "version": "0.2.60"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lunula-compose-jvm/0.2.60/lunula-compose-jvm-0.2.60.module",
        "group": "se.soderbjorn.lunula",
        "module": "lunula-compose-jvm",
        "version": "0.2.60"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lunula-compose-jvm/0.2.60/lunula-compose-jvm-0.2.60.module",
        "group": "se.soderbjorn.lunula",
        "module": "lunula-compose-jvm",
        "version": "0.2.60"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lunula-compose-jvm/0.2.60/lunula-compose-jvm-0.2.60.module",
        "group": "se.soderbjorn.lunula",
        "module": "lunula-compose-jvm",
        "version": "0.2.60"
      }
    }
  ]
}
