{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-core/0.2.36/toolkit-core-0.2.36.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-core",
    "version": "0.2.36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-jvm-0.2.36.jar",
          "url": "toolkit-core-jvm-0.2.36.jar",
          "size": 96823,
          "sha512": "1b1028de34f9023c6cb77aa15e8c1b2d054ad8364429c547febc762272f4d37a3f1a9e6851a2044032c0d2c836beb98086e6a4a7fe60eadb0b918923665a9ae6",
          "sha256": "c84a9df25a0d088b82919a8d5ab1bcc3bfefd259b01208986b3e6ad9dc39a624",
          "sha1": "b0b76c97a0ffdbf999709fad9c5ef0e90b86a822",
          "md5": "51c610d47b8a0901bc9e04ec22e94fc2"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-jvm-0.2.36.jar",
          "url": "toolkit-core-jvm-0.2.36.jar",
          "size": 96823,
          "sha512": "1b1028de34f9023c6cb77aa15e8c1b2d054ad8364429c547febc762272f4d37a3f1a9e6851a2044032c0d2c836beb98086e6a4a7fe60eadb0b918923665a9ae6",
          "sha256": "c84a9df25a0d088b82919a8d5ab1bcc3bfefd259b01208986b3e6ad9dc39a624",
          "sha1": "b0b76c97a0ffdbf999709fad9c5ef0e90b86a822",
          "md5": "51c610d47b8a0901bc9e04ec22e94fc2"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "toolkit-core-jvm-0.2.36-sources.jar",
          "url": "toolkit-core-jvm-0.2.36-sources.jar",
          "size": 41199,
          "sha512": "e04e38c67c9d1a19e14bf4f7c02d2e9eb3cad2bd0ff39c56ca41bd60a881bbe352d9a76b95120045eff43582f5e3397e54dd28aeab7bf9c529e09399a80adb97",
          "sha256": "d1d98b6ffa44abf5bf723ce841ae8490b3eee1a7cdd525f1d185d2c79998271b",
          "sha1": "e8cb8f04ed161f0dedd5bf7b71e4867e61572134",
          "md5": "f206c236df63c37a52478b5b1ccec7a6"
        }
      ]
    }
  ]
}
