{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-core/0.2.55/lunula-core-0.2.55.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-core",
    "version": "0.2.55",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-jvm-0.2.55.jar",
          "url": "lunula-core-jvm-0.2.55.jar",
          "size": 126377,
          "sha512": "84db041360e7fab57fe27af1758102c8b20ca3acd86b95ad7ea255818a220c59cb2bafb9601d6ddac39d82eac5d630a18b8d5b2b73487d5a309b2c59b138802f",
          "sha256": "e99f8e2729edd0cb0be16d92dad5d565a4bc577ed2fb24851e66b54ae069e725",
          "sha1": "68ac9b14504c437becea955cd117f559821bec2b",
          "md5": "1c7018fb518e4f094963fd49454c8f1b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-jvm-0.2.55.jar",
          "url": "lunula-core-jvm-0.2.55.jar",
          "size": 126377,
          "sha512": "84db041360e7fab57fe27af1758102c8b20ca3acd86b95ad7ea255818a220c59cb2bafb9601d6ddac39d82eac5d630a18b8d5b2b73487d5a309b2c59b138802f",
          "sha256": "e99f8e2729edd0cb0be16d92dad5d565a4bc577ed2fb24851e66b54ae069e725",
          "sha1": "68ac9b14504c437becea955cd117f559821bec2b",
          "md5": "1c7018fb518e4f094963fd49454c8f1b"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lunula-core-jvm-0.2.55-sources.jar",
          "url": "lunula-core-jvm-0.2.55-sources.jar",
          "size": 59656,
          "sha512": "8cc17426b7b2f11340f94f6dcc2253d745c696d2c7c3aac4c5691689e415b2af44faa970015547ff75f7ebbccd4b7b4c19107c3efab2084d6d21b27176a231c4",
          "sha256": "f2df68277d02a56d23e588ee2b65c182833ed1a8aad4a79c9652fc42ebbcf484",
          "sha1": "55f2c75d4db0172343b95c844361e2f60ce106c6",
          "md5": "631880777ece7b5d246fa0354a4c73a1"
        }
      ]
    }
  ]
}
