{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-core/0.2.55/lunula-core-0.2.55.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-core",
    "version": "0.2.55",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-js-0.2.55.klib",
          "url": "lunula-core-js-0.2.55.klib",
          "size": 150220,
          "sha512": "ee805b6d3b8ea4a30206eada0a73c0ce7b8cc0a751c92a1d036991e71b329a9a8c7586d08ffdea3387222eac51de7ae7e214c2af270369cd29ee5dedf44bd27d",
          "sha256": "5201319c2a04145ec357ac8d6e98e9f261a9c2d223c8ac056dcfc7a8183e1c20",
          "sha1": "dffb5c0a468a2ef7bebe328589802d988e56c504",
          "md5": "ec4807a3336c96b135b9bb829db01190"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-js-0.2.55.klib",
          "url": "lunula-core-js-0.2.55.klib",
          "size": 150220,
          "sha512": "ee805b6d3b8ea4a30206eada0a73c0ce7b8cc0a751c92a1d036991e71b329a9a8c7586d08ffdea3387222eac51de7ae7e214c2af270369cd29ee5dedf44bd27d",
          "sha256": "5201319c2a04145ec357ac8d6e98e9f261a9c2d223c8ac056dcfc7a8183e1c20",
          "sha1": "dffb5c0a468a2ef7bebe328589802d988e56c504",
          "md5": "ec4807a3336c96b135b9bb829db01190"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "lunula-core-js-0.2.55-sources.jar",
          "url": "lunula-core-js-0.2.55-sources.jar",
          "size": 59656,
          "sha512": "8cc17426b7b2f11340f94f6dcc2253d745c696d2c7c3aac4c5691689e415b2af44faa970015547ff75f7ebbccd4b7b4c19107c3efab2084d6d21b27176a231c4",
          "sha256": "f2df68277d02a56d23e588ee2b65c182833ed1a8aad4a79c9652fc42ebbcf484",
          "sha1": "55f2c75d4db0172343b95c844361e2f60ce106c6",
          "md5": "631880777ece7b5d246fa0354a4c73a1"
        }
      ]
    }
  ]
}
