{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-core/0.2.54/lunula-core-0.2.54.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-core",
    "version": "0.2.54",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-release.aar",
          "url": "lunula-core-android-0.2.54.aar",
          "size": 111810,
          "sha512": "83b28661c6294a3b057812d2f34bd0bb34a904794fc51851bd5bc51fb8d85b3ab33bc6e00bfef477fd06c77b491a8a6274c7394d3392a36b1832c50aa74cd673",
          "sha256": "a1df47b47bae7b5f9d8f3527447a00591369bfbad094b85c9719c35c3b853fab",
          "sha1": "5a7003b820decdea05312d29f68d2a99de0c33af",
          "md5": "195d6df89a600b0b165ee6c6251cd2e2"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "lunula-core-release.aar",
          "url": "lunula-core-android-0.2.54.aar",
          "size": 111810,
          "sha512": "83b28661c6294a3b057812d2f34bd0bb34a904794fc51851bd5bc51fb8d85b3ab33bc6e00bfef477fd06c77b491a8a6274c7394d3392a36b1832c50aa74cd673",
          "sha256": "a1df47b47bae7b5f9d8f3527447a00591369bfbad094b85c9719c35c3b853fab",
          "sha1": "5a7003b820decdea05312d29f68d2a99de0c33af",
          "md5": "195d6df89a600b0b165ee6c6251cd2e2"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "lunula-core-android-0.2.54-sources.jar",
          "url": "lunula-core-android-0.2.54-sources.jar",
          "size": 51667,
          "sha512": "7f63648ddc49f040f2b43f9cc2e18d4fba9fe7dec4c32ec412c50ce2a08cc39647342c32de0c9771ae9516b15d821e8a46f24543f3c2eb3c979bc85247cb64a4",
          "sha256": "b1d0c2535775be4a0acb9cfc4c839db7879edb7431658e9378359e1cb222a0ff",
          "sha1": "3c5712af96dbdda596f1715fb5ff7f47997b3d44",
          "md5": "cc14ab753f59755b35a65f9ea5d75001"
        }
      ]
    }
  ]
}
