{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-web/0.2.65/lunula-web-0.2.65.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-web",
    "version": "0.2.65",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.lunula",
          "module": "lunula-core",
          "version": {
            "requires": "0.2.65"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-web-js-0.2.65.klib",
          "url": "lunula-web-js-0.2.65.klib",
          "size": 890201,
          "sha512": "ed1d114b9fdba9808f0d7f8e6ebd6f7995e80d91e09fe91ec8587ee1104944b969a3749e58e103be6e6bf11eea7ce8942e7cc6b4e3dfce007d2d91bbada7f572",
          "sha256": "7084ddaa0db629f92dbefce4bb3be71567882af7be79527c1692cc0c0b8b203a",
          "sha1": "a9ea3d143cf96363ea82aa15e8a03909ee75cf5d",
          "md5": "52bded0c15db2f6342e83cc9ec6ea770"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.lunula",
          "module": "lunula-core",
          "version": {
            "requires": "0.2.65"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-web-js-0.2.65.klib",
          "url": "lunula-web-js-0.2.65.klib",
          "size": 890201,
          "sha512": "ed1d114b9fdba9808f0d7f8e6ebd6f7995e80d91e09fe91ec8587ee1104944b969a3749e58e103be6e6bf11eea7ce8942e7cc6b4e3dfce007d2d91bbada7f572",
          "sha256": "7084ddaa0db629f92dbefce4bb3be71567882af7be79527c1692cc0c0b8b203a",
          "sha1": "a9ea3d143cf96363ea82aa15e8a03909ee75cf5d",
          "md5": "52bded0c15db2f6342e83cc9ec6ea770"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "lunula-web-js-0.2.65-sources.jar",
          "url": "lunula-web-js-0.2.65-sources.jar",
          "size": 396897,
          "sha512": "872d62d7e17cab779ca0e46806b6955d4c4f6acc4b2095039c7ad69e5e49d8ecd33abf11b3cf60aee9cdb6cbba406beb5bc33c0b5a550c0b14958774005c9041",
          "sha256": "4162f423bd53baf6bc1760142eabc1111fc40d95ef3426e4e0c908aa41fc764a",
          "sha1": "34be6a970a01b0c10a99dee0a42f72282d50c138",
          "md5": "630a6038fefc881862eff4a4d194f855"
        }
      ]
    }
  ]
}
