{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-web/0.2.34/toolkit-web-0.2.34.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-web",
    "version": "0.2.34",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.34"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.2.34.klib",
          "url": "toolkit-web-js-0.2.34.klib",
          "size": 782862,
          "sha512": "e685b62719824b44132eedbbb46443170112eb260f55a9125ef2beda40047d31e81430aa57abd7ae07f061f09069d3ccc5cc874f0a9f927a3cb770c957f557ed",
          "sha256": "ebc5b46c3efe4256d37f27d0132d08afc997a41fdddfe118b3f3043b7ff36322",
          "sha1": "950576c81537856933e26890fbae1d7398d7ef76",
          "md5": "526cccfd3487376a2429b24999099c4e"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.34"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.2.34.klib",
          "url": "toolkit-web-js-0.2.34.klib",
          "size": 782862,
          "sha512": "e685b62719824b44132eedbbb46443170112eb260f55a9125ef2beda40047d31e81430aa57abd7ae07f061f09069d3ccc5cc874f0a9f927a3cb770c957f557ed",
          "sha256": "ebc5b46c3efe4256d37f27d0132d08afc997a41fdddfe118b3f3043b7ff36322",
          "sha1": "950576c81537856933e26890fbae1d7398d7ef76",
          "md5": "526cccfd3487376a2429b24999099c4e"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "toolkit-web-js-0.2.34-sources.jar",
          "url": "toolkit-web-js-0.2.34-sources.jar",
          "size": 336912,
          "sha512": "105d600f00c0ce3e905d5e1510a834c4eaeb414aabb79e427de43b9b2a849d9725ab657bc9d37f553e492fa439bbeaada5c24f8e0fd8172e01af289253ed956b",
          "sha256": "76f93d15b1fb4b5db256ce217092028f01509b79c60b056ef6941de14bb5ada1",
          "sha1": "b3d54cef69508d7e507ebaa80dbd232d4d734f02",
          "md5": "cd6084f1e0b6a32cb466c4944a3e8a31"
        }
      ]
    }
  ]
}
