{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-web/0.2.70/lunula-web-0.2.70.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-web",
    "version": "0.2.70",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.lunula",
          "module": "lunula-core",
          "version": {
            "requires": "0.2.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-web-js-0.2.70.klib",
          "url": "lunula-web-js-0.2.70.klib",
          "size": 912734,
          "sha512": "dfe606443bb1e185fa64993e9df6712a7d91a1838ee572b1a7a77b40ddcecf6b06f10d62beba03bd4d6f9def057d7177ff12aa6b8dedddcec05a1a14660c5b90",
          "sha256": "44705b9bd46abecff8f8129ebc83d2c8272bc89aac25e8b93876d4a550af8359",
          "sha1": "a741ec73d404ff84c81b99b2f38baa0ace5f6d4a",
          "md5": "ef3a8f3f55cd82fdf282a45ef29325aa"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.lunula",
          "module": "lunula-core",
          "version": {
            "requires": "0.2.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-web-js-0.2.70.klib",
          "url": "lunula-web-js-0.2.70.klib",
          "size": 912734,
          "sha512": "dfe606443bb1e185fa64993e9df6712a7d91a1838ee572b1a7a77b40ddcecf6b06f10d62beba03bd4d6f9def057d7177ff12aa6b8dedddcec05a1a14660c5b90",
          "sha256": "44705b9bd46abecff8f8129ebc83d2c8272bc89aac25e8b93876d4a550af8359",
          "sha1": "a741ec73d404ff84c81b99b2f38baa0ace5f6d4a",
          "md5": "ef3a8f3f55cd82fdf282a45ef29325aa"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "lunula-web-js-0.2.70-sources.jar",
          "url": "lunula-web-js-0.2.70-sources.jar",
          "size": 413597,
          "sha512": "8e8d9fdfa14b26d0d536e2d37a8903ae5cc46f98e3be4d1c17968fe78f447d8dcda676a4db5b7bde10319b74f57b2bc4279beff3e6516689ac20cfe9c9fb862e",
          "sha256": "82ef17564496609d8f9f8a5d8254ebf7986d9eeb057eaf01f6e158af0b404be0",
          "sha1": "e1dba313369c643f6093c3202b208797458e57fc",
          "md5": "5272659e40918202afca5ac10a2905bc"
        }
      ]
    }
  ]
}
