{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-core/0.2.70/lunula-core-0.2.70.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-core",
    "version": "0.2.70",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-js-0.2.70.klib",
          "url": "lunula-core-js-0.2.70.klib",
          "size": 151658,
          "sha512": "8f1f75f5b38b9f66bcbfa09e188c0227440e496c9ed011db0a8990b2132392365171f84198d5dcc634a3ea261cea48a3b34f42bbbb56d8587f8c9df268e9a97a",
          "sha256": "8c71a5eaecdae0b589fde4d32cd6b6057b1ab13369517369c4e54e29cbcfc7df",
          "sha1": "85365a85570ff6d1039587dceb8d1ffd4d3bff9d",
          "md5": "0ed1eb14bffff208dfa9b6d400c6e198"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-js-0.2.70.klib",
          "url": "lunula-core-js-0.2.70.klib",
          "size": 151658,
          "sha512": "8f1f75f5b38b9f66bcbfa09e188c0227440e496c9ed011db0a8990b2132392365171f84198d5dcc634a3ea261cea48a3b34f42bbbb56d8587f8c9df268e9a97a",
          "sha256": "8c71a5eaecdae0b589fde4d32cd6b6057b1ab13369517369c4e54e29cbcfc7df",
          "sha1": "85365a85570ff6d1039587dceb8d1ffd4d3bff9d",
          "md5": "0ed1eb14bffff208dfa9b6d400c6e198"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "lunula-core-js-0.2.70-sources.jar",
          "url": "lunula-core-js-0.2.70-sources.jar",
          "size": 61079,
          "sha512": "102db2b97a48b465efdf5975959bd14849ef65b8283c5a2f6e4f143b17e944d82f1c174e04a3cf52483f7313a230a6cba2db52d282a311af5fa497789ad8e353",
          "sha256": "c065e9de8017e55497a301dc068b6304ca49417ce1510e6f77c3445362eb9965",
          "sha1": "799c416f3d21ed5541184d6b11b01d59c182685a",
          "md5": "3e2eb269a859c901ef4513bdcfc5b14c"
        }
      ]
    }
  ]
}
