{
  "formatVersion": "1.1",
  "component": {
    "group": "se.soderbjorn.lunula",
    "module": "lunula-core",
    "version": "0.2.55",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-metadata-0.2.55.jar",
          "url": "lunula-core-0.2.55.jar",
          "size": 15570,
          "sha512": "0a52d3cad1d1ea620e218aa77da55c97b52b283e0a86f5691e55be569fc92fb7782aac5467cef396a74f641c23a2c8a452460851fc38033e9122270857d47420",
          "sha256": "aac1e013b0a97dc53bad57c2cf31bedde4feeeab02b1f3da99e508aa0e2ca41f",
          "sha1": "227a9234983e72cbc10aeb5a44a407509505dee0",
          "md5": "5c1f32c41f09be5fab8d52c804830db0"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "lunula-core-kotlin-0.2.55-sources.jar",
          "url": "lunula-core-0.2.55-sources.jar",
          "size": 59656,
          "sha512": "8cc17426b7b2f11340f94f6dcc2253d745c696d2c7c3aac4c5691689e415b2af44faa970015547ff75f7ebbccd4b7b4c19107c3efab2084d6d21b27176a231c4",
          "sha256": "f2df68277d02a56d23e588ee2b65c182833ed1a8aad4a79c9652fc42ebbcf484",
          "sha1": "55f2c75d4db0172343b95c844361e2f60ce106c6",
          "md5": "631880777ece7b5d246fa0354a4c73a1"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../lunula-core-android/0.2.55/lunula-core-android-0.2.55.module",
        "group": "se.soderbjorn.lunula",
        "module": "lunula-core-android",
        "version": "0.2.55"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../lunula-core-android/0.2.55/lunula-core-android-0.2.55.module",
        "group": "se.soderbjorn.lunula",
        "module": "lunula-core-android",
        "version": "0.2.55"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../lunula-core-android/0.2.55/lunula-core-android-0.2.55.module",
        "group": "se.soderbjorn.lunula",
        "module": "lunula-core-android",
        "version": "0.2.55"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lunula-core-iosarm64/0.2.55/lunula-core-iosarm64-0.2.55.module",
        "group": "se.soderbjorn.lunula",
        "module": "lunula-core-iosarm64",
        "version": "0.2.55"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lunula-core-iosarm64/0.2.55/lunula-core-iosarm64-0.2.55.module",
        "group": "se.soderbjorn.lunula",
        "module": "lunula-core-iosarm64",
        "version": "0.2.55"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lunula-core-iosarm64/0.2.55/lunula-core-iosarm64-0.2.55.module",
        "group": "se.soderbjorn.lunula",
        "module": "lunula-core-iosarm64",
        "version": "0.2.55"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lunula-core-iossimulatorarm64/0.2.55/lunula-core-iossimulatorarm64-0.2.55.module",
        "group": "se.soderbjorn.lunula",
        "module": "lunula-core-iossimulatorarm64",
        "version": "0.2.55"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lunula-core-iossimulatorarm64/0.2.55/lunula-core-iossimulatorarm64-0.2.55.module",
        "group": "se.soderbjorn.lunula",
        "module": "lunula-core-iossimulatorarm64",
        "version": "0.2.55"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lunula-core-iossimulatorarm64/0.2.55/lunula-core-iossimulatorarm64-0.2.55.module",
        "group": "se.soderbjorn.lunula",
        "module": "lunula-core-iossimulatorarm64",
        "version": "0.2.55"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../lunula-core-js/0.2.55/lunula-core-js-0.2.55.module",
        "group": "se.soderbjorn.lunula",
        "module": "lunula-core-js",
        "version": "0.2.55"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../lunula-core-js/0.2.55/lunula-core-js-0.2.55.module",
        "group": "se.soderbjorn.lunula",
        "module": "lunula-core-js",
        "version": "0.2.55"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../lunula-core-js/0.2.55/lunula-core-js-0.2.55.module",
        "group": "se.soderbjorn.lunula",
        "module": "lunula-core-js",
        "version": "0.2.55"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lunula-core-jvm/0.2.55/lunula-core-jvm-0.2.55.module",
        "group": "se.soderbjorn.lunula",
        "module": "lunula-core-jvm",
        "version": "0.2.55"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lunula-core-jvm/0.2.55/lunula-core-jvm-0.2.55.module",
        "group": "se.soderbjorn.lunula",
        "module": "lunula-core-jvm",
        "version": "0.2.55"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lunula-core-jvm/0.2.55/lunula-core-jvm-0.2.55.module",
        "group": "se.soderbjorn.lunula",
        "module": "lunula-core-jvm",
        "version": "0.2.55"
      }
    }
  ]
}
