{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-core/0.2.70/lunula-core-0.2.70.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-core",
    "version": "0.2.70",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-iosSimulatorArm64Main-0.2.70.klib",
          "url": "lunula-core-iossimulatorarm64-0.2.70.klib",
          "size": 179153,
          "sha512": "e75c6ec28ef5fada6a0d43f5932b29364e9a0d8279b2995a569c7ead068b8e2187c82b52b32b4622b95f45aa0a8a52b6b1fe5a2a6d7d59478faf16e2affefab5",
          "sha256": "d3cbd436ee3266221cf8c956dbd0315ca95993c49ea5cb7dda1bb9ea5eaec560",
          "sha1": "6f95d76aaebaf1b4a8db8ecbaf5a7f5afb69e796",
          "md5": "3a3aecbe04ec4461ad5a98f2f20fdece"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "lunula-core-iossimulatorarm64-0.2.70-sources.jar",
          "url": "lunula-core-iossimulatorarm64-0.2.70-sources.jar",
          "size": 61079,
          "sha512": "102db2b97a48b465efdf5975959bd14849ef65b8283c5a2f6e4f143b17e944d82f1c174e04a3cf52483f7313a230a6cba2db52d282a311af5fa497789ad8e353",
          "sha256": "c065e9de8017e55497a301dc068b6304ca49417ce1510e6f77c3445362eb9965",
          "sha1": "799c416f3d21ed5541184d6b11b01d59c182685a",
          "md5": "3e2eb269a859c901ef4513bdcfc5b14c"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-iossimulatorarm64-0.2.70-metadata.jar",
          "url": "lunula-core-iossimulatorarm64-0.2.70-metadata.jar",
          "size": 261,
          "sha512": "af1c9bd1adc1590286958be3d8e449ddf1121460a15407777a2219ad52ce0c1790e3b03ed89e0df5ae6d59bcd2518e3bb0b1e49bda50e935560939b9e034b20d",
          "sha256": "1bd676afdd527c91c81c6863caf008dbe2c5aef592d942cb4b5a84dc67e5ac48",
          "sha1": "efb83e04ee3323057e6dd0311aefda192f90bda9",
          "md5": "342e9815544e74bed5f175eac3f75793"
        }
      ]
    }
  ]
}
