{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-core/0.2.71/lunula-core-0.2.71.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-core",
    "version": "0.2.71",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-release.aar",
          "url": "lunula-core-android-0.2.71.aar",
          "size": 121967,
          "sha512": "55910bb52ab8436469c855ce488cedcfd96495c68d0223231dcac785564d9d97cdd926b8490eb81d605273bfda6590cf708a0d9d346cdaf0ee2808a81cdc76a0",
          "sha256": "571e841a9865188e334d6bc67a7685af8646c060f02fd7868726f94eef91f4ac",
          "sha1": "0c8df16c89f40231daf7eeb287f17dd221adc5a1",
          "md5": "b033b3a07f84284a1bb776e5143e0553"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "lunula-core-release.aar",
          "url": "lunula-core-android-0.2.71.aar",
          "size": 121967,
          "sha512": "55910bb52ab8436469c855ce488cedcfd96495c68d0223231dcac785564d9d97cdd926b8490eb81d605273bfda6590cf708a0d9d346cdaf0ee2808a81cdc76a0",
          "sha256": "571e841a9865188e334d6bc67a7685af8646c060f02fd7868726f94eef91f4ac",
          "sha1": "0c8df16c89f40231daf7eeb287f17dd221adc5a1",
          "md5": "b033b3a07f84284a1bb776e5143e0553"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "lunula-core-android-0.2.71-sources.jar",
          "url": "lunula-core-android-0.2.71-sources.jar",
          "size": 62398,
          "sha512": "43b873bd9d3a1764748e86de102b9a89b1edf1f2d221dda7abb29214722efbd13e47091bbf6e563d20af7a241045ce8bc3dd96edcb98fe365fc2b4d01cda9013",
          "sha256": "43281ae31e0b5eed62718c5e00ed29c84e173f896758ca7057d7ef8d69a53309",
          "sha1": "36743746e8e894067c267c7e5bf6a6ddd8521124",
          "md5": "0109a4ddf9a308488284e0a4443bfaca"
        }
      ]
    }
  ]
}
