{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-compose/0.2.62/lunula-compose-0.2.62.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-compose",
    "version": "0.2.62",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.lunula",
          "module": "lunula-core",
          "version": {
            "requires": "0.2.62"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-compose-jvm-0.2.62.jar",
          "url": "lunula-compose-jvm-0.2.62.jar",
          "size": 30595,
          "sha512": "67c6dd457fc3b73de0d37c5f3000f60fde66ed8808fad7773fa0324bdd41bad7746a0d274b413d6e0946d348e2fb790a8975fd20ee2617e73756ea6177ab8174",
          "sha256": "f7142b8cba9b63acd0a0370f64e107fd27b6594673bb993dba46382408fded73",
          "sha1": "1e8a0fa6495abe0a582407b4c8affc6e7388ea16",
          "md5": "f58f8c6fab4116e9767d8609c1cf2948"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.lunula",
          "module": "lunula-core",
          "version": {
            "requires": "0.2.62"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-compose-jvm-0.2.62.jar",
          "url": "lunula-compose-jvm-0.2.62.jar",
          "size": 30595,
          "sha512": "67c6dd457fc3b73de0d37c5f3000f60fde66ed8808fad7773fa0324bdd41bad7746a0d274b413d6e0946d348e2fb790a8975fd20ee2617e73756ea6177ab8174",
          "sha256": "f7142b8cba9b63acd0a0370f64e107fd27b6594673bb993dba46382408fded73",
          "sha1": "1e8a0fa6495abe0a582407b4c8affc6e7388ea16",
          "md5": "f58f8c6fab4116e9767d8609c1cf2948"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lunula-compose-jvm-0.2.62-sources.jar",
          "url": "lunula-compose-jvm-0.2.62-sources.jar",
          "size": 5640,
          "sha512": "c8a81e5c5088c44475d6d69bebaf21aaedeb9cec73a717ceff9e2d30d102b9ee15fb04ef8b10e7e6586a28a394e1d69479b4148a2b50397ee6e35cf522ecb98f",
          "sha256": "2c0e5c4c1f4fe2d1828a0319658284def9e811c3bcab153e8bd3e4c878e84c47",
          "sha1": "866300d7c0979e59b50041ba034a4ebe4fe1b753",
          "md5": "34c8d35d812ec9ee8e8afdf8d5bec62e"
        }
      ]
    }
  ]
}
