{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-store/0.2.61/lunula-store-0.2.61.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-store",
    "version": "0.2.61",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "se.soderbjorn.lunula",
          "module": "lunula-core",
          "version": {
            "requires": "0.2.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-store-js-0.2.61.klib",
          "url": "lunula-store-js-0.2.61.klib",
          "size": 54484,
          "sha512": "80a58e067d6b44632cc20ae113865f00a8ca6b23b0a1c3c540f787040cecf9fccf04e829dc48164d05d9e2e3e80495192bb27615af3aa9d5148bd50e76733f9b",
          "sha256": "52fad78a39bf652829217dc0472fa979034b769a538b0e1bc3eb38902ef9a79b",
          "sha1": "291971bd0bdaa5af9f91cac3c1b1674a364533d8",
          "md5": "7256334de6c818a653d0f06a7b00c9b9"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "se.soderbjorn.lunula",
          "module": "lunula-core",
          "version": {
            "requires": "0.2.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-store-js-0.2.61.klib",
          "url": "lunula-store-js-0.2.61.klib",
          "size": 54484,
          "sha512": "80a58e067d6b44632cc20ae113865f00a8ca6b23b0a1c3c540f787040cecf9fccf04e829dc48164d05d9e2e3e80495192bb27615af3aa9d5148bd50e76733f9b",
          "sha256": "52fad78a39bf652829217dc0472fa979034b769a538b0e1bc3eb38902ef9a79b",
          "sha1": "291971bd0bdaa5af9f91cac3c1b1674a364533d8",
          "md5": "7256334de6c818a653d0f06a7b00c9b9"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "lunula-store-js-0.2.61-sources.jar",
          "url": "lunula-store-js-0.2.61-sources.jar",
          "size": 17713,
          "sha512": "99919941874b75d47564faffacd8b85aa04947dd7c2ddb26a3a1525447c6d40d2e121a93518916e570373f9a3bff466861d4ccb402b7889165f08e7a62175960",
          "sha256": "d6a53146e89d3b7dd08aa57e2e64227004026364435226f9b0af887a236d7a6e",
          "sha1": "65a01e4361f359356dc810e46d4ed40497936870",
          "md5": "431c0e9f09bcd0de6676b73127b9144a"
        }
      ]
    }
  ]
}
