{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-core/0.2.60/lunula-core-0.2.60.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-core",
    "version": "0.2.60",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-js-0.2.60.klib",
          "url": "lunula-core-js-0.2.60.klib",
          "size": 150313,
          "sha512": "27701f5372cc8ee0ff04521d332f135ed9cfba5585d110eda9ed4be2c17793ab76c9f941673ecaa3a78cf5ad2b6b5a2df9323df18b0f33e056b48ce16b25de59",
          "sha256": "cd725fb0f0bcccfbb48f544901630967417cb5a7d778d411e3c04c0bd8d12a50",
          "sha1": "da2a5a0f6855b922cb128353b72846023aa75edf",
          "md5": "e6663ce8337160960f71b96706f41b7a"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-js-0.2.60.klib",
          "url": "lunula-core-js-0.2.60.klib",
          "size": 150313,
          "sha512": "27701f5372cc8ee0ff04521d332f135ed9cfba5585d110eda9ed4be2c17793ab76c9f941673ecaa3a78cf5ad2b6b5a2df9323df18b0f33e056b48ce16b25de59",
          "sha256": "cd725fb0f0bcccfbb48f544901630967417cb5a7d778d411e3c04c0bd8d12a50",
          "sha1": "da2a5a0f6855b922cb128353b72846023aa75edf",
          "md5": "e6663ce8337160960f71b96706f41b7a"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "lunula-core-js-0.2.60-sources.jar",
          "url": "lunula-core-js-0.2.60-sources.jar",
          "size": 60183,
          "sha512": "5863c1ed2855f567a5bf249f66b3ec444e2ef8ed50ad90c818bcbdae15f5e9cb03fbd6eab8dde23a3c4f671da6cd1261fa2a44f612230eabfad6dce2b2ebe775",
          "sha256": "a8467f5f7638e6cc2e9c3c700bd397a5ad8d4b792a80bf83a8aad249a960f81c",
          "sha1": "02e1b688c16da8d448e605ff82ff763a9c055e90",
          "md5": "a550be4c6ad0392b7b303e0b0e9b5db1"
        }
      ]
    }
  ]
}
