{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-core/0.2.55/lunula-core-0.2.55.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-core",
    "version": "0.2.55",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-iosArm64Main-0.2.55.klib",
          "url": "lunula-core-iosarm64-0.2.55.klib",
          "size": 177071,
          "sha512": "b07aa74cb72909b103e5c6459cc6c9ea90c0f0194d7b63f039fa1fdc449ab730d1a36db87fed4c72913ae4aef1b28c30ae32c85ab3c70740cb0b3d4667ed5624",
          "sha256": "b675c93cf95ba9362874b12dcc793307b093a3b59a01947af4cda99938d02cca",
          "sha1": "4e183a729887548a7e4f9261aef0d2b26912a4d0",
          "md5": "75d5971c4a5a6f37e845744474b8f832"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "lunula-core-iosarm64-0.2.55-sources.jar",
          "url": "lunula-core-iosarm64-0.2.55-sources.jar",
          "size": 59656,
          "sha512": "8cc17426b7b2f11340f94f6dcc2253d745c696d2c7c3aac4c5691689e415b2af44faa970015547ff75f7ebbccd4b7b4c19107c3efab2084d6d21b27176a231c4",
          "sha256": "f2df68277d02a56d23e588ee2b65c182833ed1a8aad4a79c9652fc42ebbcf484",
          "sha1": "55f2c75d4db0172343b95c844361e2f60ce106c6",
          "md5": "631880777ece7b5d246fa0354a4c73a1"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-iosarm64-0.2.55-metadata.jar",
          "url": "lunula-core-iosarm64-0.2.55-metadata.jar",
          "size": 261,
          "sha512": "0052a0d20360de668138b9a9c953a51cb08e39bfb613357b23fa88903e830ef70c8ed90a95f86223946c7e09ce14f07e82f60410549894e4e06e33ec556563fa",
          "sha256": "b8013be5cef1129dd4ab6adfece3848b2e7e6ddfcd2b4fe488abeff60ef7970c",
          "sha1": "a704e1c15b6783b447f5ea72333e8ffe55014cbd",
          "md5": "041d75a3c25f1b391f57cbfb771aab74"
        }
      ]
    }
  ]
}
