{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-core/0.2.69/lunula-core-0.2.69.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-core",
    "version": "0.2.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-jvm-0.2.69.jar",
          "url": "lunula-core-jvm-0.2.69.jar",
          "size": 127548,
          "sha512": "e5c8253e2f6c0d26f7afd937d7db3fd635c8dbc60836d3d6d0de85f846d4579062063f9c110aeaf200ed47ad8018d1dd5a4a8860061579150b48b0069849703e",
          "sha256": "78af913edd95c6185219479e961990e0d6bfea7cda694bea94c250e7009b22f8",
          "sha1": "211e5640490a2b5b46c8bbc5b712467d6615d3b0",
          "md5": "d92b18f8483a36fc96ba8134aeb0a23c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-jvm-0.2.69.jar",
          "url": "lunula-core-jvm-0.2.69.jar",
          "size": 127548,
          "sha512": "e5c8253e2f6c0d26f7afd937d7db3fd635c8dbc60836d3d6d0de85f846d4579062063f9c110aeaf200ed47ad8018d1dd5a4a8860061579150b48b0069849703e",
          "sha256": "78af913edd95c6185219479e961990e0d6bfea7cda694bea94c250e7009b22f8",
          "sha1": "211e5640490a2b5b46c8bbc5b712467d6615d3b0",
          "md5": "d92b18f8483a36fc96ba8134aeb0a23c"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lunula-core-jvm-0.2.69-sources.jar",
          "url": "lunula-core-jvm-0.2.69-sources.jar",
          "size": 61079,
          "sha512": "102db2b97a48b465efdf5975959bd14849ef65b8283c5a2f6e4f143b17e944d82f1c174e04a3cf52483f7313a230a6cba2db52d282a311af5fa497789ad8e353",
          "sha256": "c065e9de8017e55497a301dc068b6304ca49417ce1510e6f77c3445362eb9965",
          "sha1": "799c416f3d21ed5541184d6b11b01d59c182685a",
          "md5": "3e2eb269a859c901ef4513bdcfc5b14c"
        }
      ]
    }
  ]
}
