{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-core/0.2.55/lunula-core-0.2.55.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-core",
    "version": "0.2.55",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-release.aar",
          "url": "lunula-core-android-0.2.55.aar",
          "size": 120730,
          "sha512": "0d5432b2f43ea8e3cf02a0abb3ef064a97a872fda96a94d7216288d2ad8e747cab162a70cf658b813499155f3030b691674ae8e83d942d3041dc3353968a4d22",
          "sha256": "9f16e4fc06fd34ef2c6d64259df891e502c6519c96b81f9e1fc2b523e5ad663c",
          "sha1": "3ba5b8a7aa2d8aea9b806550b45482c566d85bf8",
          "md5": "34bfcd41537a1e40dbf1df23cf2a00dc"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "lunula-core-release.aar",
          "url": "lunula-core-android-0.2.55.aar",
          "size": 120730,
          "sha512": "0d5432b2f43ea8e3cf02a0abb3ef064a97a872fda96a94d7216288d2ad8e747cab162a70cf658b813499155f3030b691674ae8e83d942d3041dc3353968a4d22",
          "sha256": "9f16e4fc06fd34ef2c6d64259df891e502c6519c96b81f9e1fc2b523e5ad663c",
          "sha1": "3ba5b8a7aa2d8aea9b806550b45482c566d85bf8",
          "md5": "34bfcd41537a1e40dbf1df23cf2a00dc"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "lunula-core-android-0.2.55-sources.jar",
          "url": "lunula-core-android-0.2.55-sources.jar",
          "size": 59656,
          "sha512": "8cc17426b7b2f11340f94f6dcc2253d745c696d2c7c3aac4c5691689e415b2af44faa970015547ff75f7ebbccd4b7b4c19107c3efab2084d6d21b27176a231c4",
          "sha256": "f2df68277d02a56d23e588ee2b65c182833ed1a8aad4a79c9652fc42ebbcf484",
          "sha1": "55f2c75d4db0172343b95c844361e2f60ce106c6",
          "md5": "631880777ece7b5d246fa0354a4c73a1"
        }
      ]
    }
  ]
}
